/*** Autogenerated by WIDL 10.17 - Do not edit ***/

#define PROXY_DELEGATION
#include <objbase.h>
#include <rpcproxy.h>

#ifdef __cplusplus
extern "C" {
#endif

EXTERN_PROXY_FILE(oaidl)
EXTERN_PROXY_FILE(objidl)
EXTERN_PROXY_FILE(unknwn)
EXTERN_PROXY_FILE(oleidl)
EXTERN_PROXY_FILE(propidl)

PROXYFILE_LIST_START
/* Start of list */
  REFERENCE_PROXY_FILE(oaidl),
  REFERENCE_PROXY_FILE(objidl),
  REFERENCE_PROXY_FILE(unknwn),
  REFERENCE_PROXY_FILE(oleidl),
  REFERENCE_PROXY_FILE(propidl),
/* End of list */
PROXYFILE_LIST_END

DLLDATA_ROUTINES(aProxyFileList, GET_DLL_CLSID)

#ifdef __cplusplus
}
#endif

