/*** Autogenerated by WIDL 10.17 from oleidl.idl - Do not edit ***/
#include <string.h>

#include "oleidl.h"

#define TYPE_FORMAT_STRING_SIZE 3
#define PROC_FORMAT_STRING_SIZE 1

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const USER_MARSHAL_ROUTINE_QUADRUPLE UserMarshalRoutines[] =
{
    {
        (USER_MARSHAL_SIZING_ROUTINE)HWND_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)HWND_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)HWND_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)HWND_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)HMENU_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)HMENU_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)HMENU_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)HMENU_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)HGLOBAL_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)HGLOBAL_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)HGLOBAL_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)HGLOBAL_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)HACCEL_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)HACCEL_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)HACCEL_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)HACCEL_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)CLIPFORMAT_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)CLIPFORMAT_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)CLIPFORMAT_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)CLIPFORMAT_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)STGMEDIUM_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)STGMEDIUM_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)STGMEDIUM_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)STGMEDIUM_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)HDC_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)HDC_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)HDC_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)HDC_UserFree
    }
};

/*****************************************************************************
 * IOLETypes interface
 */

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
        0x0
    }
};

