/*** Autogenerated by WIDL 10.17 from unknwn.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "unknwn.h"

#define TYPE_FORMAT_STRING_SIZE 37
#define PROC_FORMAT_STRING_SIZE 83

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IClassFactory interface
 */
HRESULT STDMETHODCALLTYPE IClassFactory_RemoteCreateInstance_Proxy(
    IClassFactory* This,
    REFIID riid,
    IUnknown **ppvObject)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &Object_StubDesc,
                              &__MIDL_ProcFormatString.Format[0],
                              This,
                              riid,
                              ppvObject );
    return (HRESULT)_RetVal.Simple;
}

void __RPC_API IClassFactory_RemoteCreateInstance_Thunk( PMIDL_STUB_MESSAGE pStubMsg )
{
    struct _PARAM_STRUCT
    {
        IClassFactory *This;
        REFIID riid;
        IUnknown **ppvObject;
        HRESULT DECLSPEC_ALIGN(8) _RetVal;
    } *pParamStruct = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pParamStruct->_RetVal = IClassFactory_CreateInstance_Stub( pParamStruct->This,
        pParamStruct->riid,
        pParamStruct->ppvObject );
}

HRESULT STDMETHODCALLTYPE IClassFactory_RemoteLockServer_Proxy(
    IClassFactory* This,
    BOOL fLock)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &Object_StubDesc,
                              &__MIDL_ProcFormatString.Format[44],
                              This,
                              fLock );
    return (HRESULT)_RetVal.Simple;
}

void __RPC_API IClassFactory_RemoteLockServer_Thunk( PMIDL_STUB_MESSAGE pStubMsg )
{
    struct _PARAM_STRUCT
    {
        IClassFactory *This;
        BOOL DECLSPEC_ALIGN(8) fLock;
        HRESULT DECLSPEC_ALIGN(8) _RetVal;
    } *pParamStruct = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pParamStruct->_RetVal = IClassFactory_LockServer_Stub( pParamStruct->This,
        pParamStruct->fLock );
}

static const unsigned short IClassFactory_FormatStringOffsetTable[] =
{
    0,  /* IClassFactory::RemoteCreateInstance */
    44,  /* IClassFactory::RemoteLockServer */
};

static const MIDL_STUBLESS_PROXY_INFO IClassFactory_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IClassFactory_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(5) _IClassFactoryProxyVtbl =
{
    {
        &IClassFactory_ProxyInfo,
        &IID_IClassFactory,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        IClassFactory_CreateInstance_Proxy,
        IClassFactory_LockServer_Proxy,
    }
};

static const STUB_THUNK IClassFactory_StubThunkTable[] =
{
    IClassFactory_RemoteCreateInstance_Thunk,
    IClassFactory_RemoteLockServer_Thunk,
};

static const MIDL_SERVER_INFO IClassFactory_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IClassFactory_FormatStringOffsetTable[-3],
    &IClassFactory_StubThunkTable[-3],
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IClassFactoryStubVtbl =
{
    {
        &IID_IClassFactory,
        &IClassFactory_ServerInfo,
        5,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IClassFactory::RemoteCreateInstance) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter riid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 32 (parameter ppvObject) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x20),	/* type offset = 32 */
/* 38 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 44 (procedure IClassFactory::RemoteLockServer) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 70 (parameter fLock) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 76 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 8 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (2) */
        0x5b,	/* FC_END */
/* 20 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (8) */
/* 24 (IUnknown *) */
        0x2f,  /* FC_IP */
        0x5c,  /* FC_PAD */
        0x2b,	/* Corr desc: parameter riid, FC_HYPER */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x5),
/* 32 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xfff6),	/* Offset= -10 (24) */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _unknwn_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IClassFactoryProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _unknwn_StubVtblList[] =
{
    &_IClassFactoryStubVtbl,
    0
};

static PCInterfaceName const _unknwn_InterfaceNamesList[] =
{
    "IClassFactory",
    0
};

static int __stdcall _unknwn_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 0;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_unknwn, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo unknwn_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_unknwn_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_unknwn_StubVtblList,
    _unknwn_InterfaceNamesList,
    0,
    _unknwn_IID_Lookup,
    1,
    2,
    0,
    0,
    0,
    0
};
